# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
target 'DragonPoints' do
    #图片查看器
pod 'MWPhotoBrowser', '~> 2.1.0'
#分享
pod 'ShareSDK3', '~> 3.4.0'

#选择本地图片库
pod 'ZYQAssetPickerController', '~> 1.0.0'
# Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
pod 'MOBFoundation'
pod 'AFNetworking', '~> 2.1.0'
#极光推送
#pod 'JPush-iOS-SDK', '~> 2.1.8'
# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'ShareSDK3/ShareSDKUI'

# 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

pod 'BaiduMapKit' #百度地图SDK

  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DragonPoints

  target 'DragonPointsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DragonPointsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
